import Program from "./ProgramsLayout";

const Computer = () => {
  
const impacts = [
    {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    },
     {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    },
    {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    },
    {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    },
    {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    },
    {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    },
    {
      impact: "The Community impact",
      desc: "WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE. WHERE THE MAN LAYS FLAT ON HIS BACK AND THE WOMAN SITS ON HIS PENIS WHILE FACING HIM. THIS IS EVERY MAN’S FAVORITE COZ HE GETS TO CHILL WHILE YOU DO THE HARD WORK. TO MAKE THE WORK EASIER, GET YOUR HANDS DOWN THEN AND ADD TO THE GROOVE"
    }
    
    ];
    
const desc = "it doesn't matter if the the add button is the one clicked or linker, it always creates a new note. I want it to create a new note when the AddButton is clicked and review/update a note when the linker correspondent to the note is clicked. " ;

const beneGridLeft = [
  {url: "/images/displayerpic.png"},
  {url: "/images/displayerpic.png"}
  ];
const beneGridRight = [
  {url: "/images/displayerpic.png"},
  {url: "/images/displayerpic.png"},
  {url: "/images/displayerpic.png"}
  ];
  
  
  return(
     <div className="">
       <Program leadImage="/images/displayerpic.png" programName="Youth Computer Program 🏋‍♂️" programDesc={desc} bgColor=" " supportImage="/images/displayerpic.png" supportAuthor="Steve Kiza" impacts={impacts} beneGridLeft={beneGridLeft} beneGridRight={beneGridRight} />
     </div>
    
    );
};

export default Computer;